VFS.Include("LuaRules/utilities.lua")
VFS.Include("libs/teal/integration.lua")
Spring.Echo("Synced LuaRules: starting loading")
VFS.Include("LuaRules/gadgets.lua", nil, VFS.GAME)
Spring.Echo("Synced LuaRules: finished loading")
